version: "3"
services:
  app:
    build: .
    command: npm run start
    ports:
      - "4000:4000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  test:
    build: .
    command: npm run test
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
